# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milestone2.ui'
#
# Created: Thu Mar 27 17:27:11 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1038, 285)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_2.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_2.setSizePolicy(sizePolicy)
        self.commandLinkButton_2.setMinimumSize(QtCore.QSize(147, 10))
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName(_fromUtf8("commandLinkButton_2"))
        self.gridLayout.addWidget(self.commandLinkButton_2, 6, 0, 1, 1)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.gridLayout.addWidget(self.commandLinkButton, 6, 5, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 4, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.frame)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 4, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.frame)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.frame)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_4, 2, 3, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.frame)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_7, 3, 3, 1, 1)
        self.comboBox_10 = QtGui.QComboBox(self.frame)
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_10, 4, 3, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.frame)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 1, 4, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.frame)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_5, 2, 4, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.frame)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_8, 3, 4, 1, 1)
        self.comboBox_11 = QtGui.QComboBox(self.frame)
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_11, 4, 4, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.frame)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_3, 1, 5, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.frame)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_6, 2, 5, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.frame)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_9, 3, 5, 1, 1)
        self.comboBox_12 = QtGui.QComboBox(self.frame)
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_12, 4, 5, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.frame)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_9.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 1, 2, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.frame)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_10.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 2, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.frame)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_11.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout.addWidget(self.lineEdit_11, 3, 2, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.frame)
        self.lineEdit_12.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout.addWidget(self.lineEdit_12, 4, 2, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))
        self.actionUpdate_Apps = QtGui.QAction(MainWindow)
        self.actionUpdate_Apps.setObjectName(_fromUtf8("actionUpdate_Apps"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionUpdate_Apps)
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL(_fromUtf8("activated()")), self.comboBox.clearEditText)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL(_fromUtf8("activated()")), self.comboBox_4.clearEditText)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL(_fromUtf8("activated()")), self.comboBox_7.clearEditText)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL(_fromUtf8("activated()")), self.comboBox_10.clearEditText)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QtTurnKey Install Assistant", None))
        self.label.setText(_translate("MainWindow", "Turnkey Application", None))
        self.label_2.setText(_translate("MainWindow", "Virtualization Type", None))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Save", None))
        self.commandLinkButton.setText(_translate("MainWindow", "Install", None))
        self.checkBox.setText(_translate("MainWindow", "Load From File", None))
        self.lineEdit.setText(_translate("MainWindow", "Target Master IP", None))
        self.label_3.setText(_translate("MainWindow", "Connection Method", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Login", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Etherpad Lite", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Joomla", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Drupal 7", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "ASP .NET on Apache with Mod Mono", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "Sahana Eden", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "Ushahidi", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "GitLab", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "CouchDB", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "LAMP Stack", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "Google AppEngine on SDK", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "Google AppEngine Python SDK", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "Google AppEngine Java SDK", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "Elgg", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "Concrete5", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "eZ publish", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "e107", None))
        self.comboBox.setItemText(16, _translate("MainWindow", "Collabtive", None))
        self.comboBox.setItemText(17, _translate("MainWindow", "CodeIgniter", None))
        self.comboBox.setItemText(18, _translate("MainWindow", "AppFlower", None))
        self.comboBox.setItemText(19, _translate("MainWindow", "b2evolution", None))
        self.comboBox.setItemText(20, _translate("MainWindow", "BambooInvoice", None))
        self.comboBox.setItemText(21, _translate("MainWindow", "MongoDB", None))
        self.comboBox.setItemText(22, _translate("MainWindow", "Mibew", None))
        self.comboBox.setItemText(23, _translate("MainWindow", "Nginx PHP FastCGI Server Configuration", None))
        self.comboBox.setItemText(24, _translate("MainWindow", "Clipbucket", None))
        self.comboBox.setItemText(25, _translate("MainWindow", "Canvas", None))
        self.comboBox.setItemText(26, _translate("MainWindow", "CakePHP", None))
        self.comboBox.setItemText(27, _translate("MainWindow", "node.js", None))
        self.comboBox.setItemText(28, _translate("MainWindow", "iceScrum", None))
        self.comboBox.setItemText(29, _translate("MainWindow", "Jenkins", None))
        self.comboBox.setItemText(30, _translate("MainWindow", "Mambo", None))
        self.comboBox.setItemText(31, _translate("MainWindow", "Mahara", None))
        self.comboBox.setItemText(32, _translate("MainWindow", "Lighttpd PHP FastCGI Configuration", None))
        self.comboBox.setItemText(33, _translate("MainWindow", "OpenLDAP", None))
        self.comboBox.setItemText(34, _translate("MainWindow", "osCommerce", None))
        self.comboBox.setItemText(35, _translate("MainWindow", "Omeka", None))
        self.comboBox.setItemText(36, _translate("MainWindow", "Plone", None))
        self.comboBox.setItemText(37, _translate("MainWindow", "LimeSurvey", None))
        self.comboBox.setItemText(38, _translate("MainWindow", "OrangeHRM", None))
        self.comboBox.setItemText(39, _translate("MainWindow", "OpenPhoto", None))
        self.comboBox.setItemText(40, _translate("MainWindow", "Piwik", None))
        self.comboBox.setItemText(41, _translate("MainWindow", "Pligg", None))
        self.comboBox.setItemText(42, _translate("MainWindow", "SilverStripe", None))
        self.comboBox.setItemText(43, _translate("MainWindow", "PunBB", None))
        self.comboBox.setItemText(44, _translate("MainWindow", "ProcessMaker", None))
        self.comboBox.setItemText(45, _translate("MainWindow", "Sencha", None))
        self.comboBox.setItemText(46, _translate("MainWindow", "OSQA", None))
        self.comboBox.setItemText(47, _translate("MainWindow", "ownCloud", None))
        self.comboBox.setItemText(48, _translate("MainWindow", "phpList", None))
        self.comboBox.setItemText(49, _translate("MainWindow", "PHP-Nuke", None))
        self.comboBox.setItemText(50, _translate("MainWindow", "Vanilla Forum", None))
        self.comboBox.setItemText(51, _translate("MainWindow", "web2py", None))
        self.comboBox.setItemText(52, _translate("MainWindow", "Phreedom", None))
        self.comboBox.setItemText(53, _translate("MainWindow", "Typo3", None))
        self.comboBox.setItemText(54, _translate("MainWindow", "TomatoCart", None))
        self.comboBox.setItemText(55, _translate("MainWindow", "XOOPS", None))
        self.comboBox.setItemText(56, _translate("MainWindow", "Zurmo", None))
        self.comboBox.setItemText(57, _translate("MainWindow", "SiT! Support Incident Tracker", None))
        self.comboBox.setItemText(58, _translate("MainWindow", "SimpleInvoices", None))
        self.comboBox.setItemText(59, _translate("MainWindow", "SimpleMachines", None))
        self.comboBox.setItemText(60, _translate("MainWindow", "SugarCRM", None))
        self.comboBox.setItemText(61, _translate("MainWindow", "Zen Cart", None))
        self.comboBox.setItemText(62, _translate("MainWindow", "Yii Framework", None))
        self.comboBox.setItemText(63, _translate("MainWindow", "Ruby on Rails", None))
        self.comboBox.setItemText(64, _translate("MainWindow", "File Server", None))
        self.comboBox.setItemText(65, _translate("MainWindow", "WordPress", None))
        self.comboBox.setItemText(66, _translate("MainWindow", "Redmine", None))
        self.comboBox.setItemText(67, _translate("MainWindow", "OTRS", None))
        self.comboBox.setItemText(68, _translate("MainWindow", "MediaWiki", None))
        self.comboBox.setItemText(69, _translate("MainWindow", "PrestaShop", None))
        self.comboBox.setItemText(70, _translate("MainWindow", "LAPP", None))
        self.comboBox.setItemText(71, _translate("MainWindow", "Magento", None))
        self.comboBox.setItemText(72, _translate("MainWindow", "PostgreSQL", None))
        self.comboBox.setItemText(73, _translate("MainWindow", "Django", None))
        self.comboBox.setItemText(74, _translate("MainWindow", "LXC", None))
        self.comboBox.setItemText(75, _translate("MainWindow", "Observium", None))
        self.comboBox.setItemText(76, _translate("MainWindow", "Tendenci", None))
        self.comboBox.setItemText(77, _translate("MainWindow", "OpenVPN", None))
        self.comboBox.setItemText(78, _translate("MainWindow", "TKLDev", None))
        self.comboBox.setItemText(79, _translate("MainWindow", "MySQL", None))
        self.comboBox.setItemText(80, _translate("MainWindow", "phpBB", None))
        self.comboBox.setItemText(81, _translate("MainWindow", "Tomcat on Apache", None))
        self.comboBox.setItemText(82, _translate("MainWindow", "Standalone Tomcat", None))
        self.comboBox.setItemText(83, _translate("MainWindow", "MindTouch Core", None))
        self.comboBox.setItemText(84, _translate("MainWindow", "Tracks", None))
        self.comboBox.setItemText(85, _translate("MainWindow", "Symfony", None))
        self.comboBox.setItemText(86, _translate("MainWindow", "ProjectPier", None))
        self.comboBox.setItemText(87, _translate("MainWindow", "ejabberd", None))
        self.comboBox.setItemText(88, _translate("MainWindow", "TurnKey Core", None))
        self.comboBox.setItemText(89, _translate("MainWindow", "TWiki", None))
        self.comboBox.setItemText(90, _translate("MainWindow", "Domain Controller", None))
        self.comboBox.setItemText(91, _translate("MainWindow", "Revision Control", None))
        self.comboBox.setItemText(92, _translate("MainWindow", "Torrent Server", None))
        self.comboBox.setItemText(93, _translate("MainWindow", "Bugzilla", None))
        self.comboBox.setItemText(94, _translate("MainWindow", "Gallery", None))
        self.comboBox.setItemText(95, _translate("MainWindow", "Moodle", None))
        self.comboBox.setItemText(96, _translate("MainWindow", "Mantis", None))
        self.comboBox.setItemText(97, _translate("MainWindow", "Movable Type", None))
        self.comboBox.setItemText(98, _translate("MainWindow", "vTiger CRM", None))
        self.comboBox.setItemText(99, _translate("MainWindow", "StatusNet", None))
        self.comboBox.setItemText(100, _translate("MainWindow", "MoinMoin", None))
        self.comboBox.setItemText(101, _translate("MainWindow", "Roundup", None))
        self.comboBox.setItemText(102, _translate("MainWindow", "Trac", None))
        self.comboBox.setItemText(103, _translate("MainWindow", "DokuWiki", None))
        self.comboBox.setItemText(104, _translate("MainWindow", "Drupal 6", None))
        self.comboBox.setItemText(105, _translate("MainWindow", "Joomla 1.5 Appliance", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Etherpad Lite", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Joomla", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Drupal 7", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "ASP .NET on Apache with Mod Mono", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Sahana Eden", None))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Ushahidi", None))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "GitLab", None))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "CouchDB", None))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "LAMP Stack", None))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "Google AppEngine on SDK", None))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "Google AppEngine Python SDK", None))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "Google AppEngine Java SDK", None))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "Elgg", None))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "Concrete5", None))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "eZ publish", None))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "e107", None))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "Collabtive", None))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "CodeIgniter", None))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "AppFlower", None))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "b2evolution", None))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "BambooInvoice", None))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "MongoDB", None))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "Mibew", None))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "Nginx PHP FastCGI Server Configuration", None))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "Clipbucket", None))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "Canvas", None))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "CakePHP", None))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "node.js", None))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "iceScrum", None))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "Jenkins", None))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "Mambo", None))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "Mahara", None))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "Lighttpd PHP FastCGI Configuration", None))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "OpenLDAP", None))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "osCommerce", None))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "Omeka", None))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "Plone", None))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "LimeSurvey", None))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "OrangeHRM", None))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "OpenPhoto", None))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "Piwik", None))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "Pligg", None))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "SilverStripe", None))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "PunBB", None))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "ProcessMaker", None))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "Sencha", None))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "OSQA", None))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "ownCloud", None))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "phpList", None))
        self.comboBox_4.setItemText(49, _translate("MainWindow", "PHP-Nuke", None))
        self.comboBox_4.setItemText(50, _translate("MainWindow", "Vanilla Forum", None))
        self.comboBox_4.setItemText(51, _translate("MainWindow", "web2py", None))
        self.comboBox_4.setItemText(52, _translate("MainWindow", "Phreedom", None))
        self.comboBox_4.setItemText(53, _translate("MainWindow", "Typo3", None))
        self.comboBox_4.setItemText(54, _translate("MainWindow", "TomatoCart", None))
        self.comboBox_4.setItemText(55, _translate("MainWindow", "XOOPS", None))
        self.comboBox_4.setItemText(56, _translate("MainWindow", "Zurmo", None))
        self.comboBox_4.setItemText(57, _translate("MainWindow", "SiT! Support Incident Tracker", None))
        self.comboBox_4.setItemText(58, _translate("MainWindow", "SimpleInvoices", None))
        self.comboBox_4.setItemText(59, _translate("MainWindow", "SimpleMachines", None))
        self.comboBox_4.setItemText(60, _translate("MainWindow", "SugarCRM", None))
        self.comboBox_4.setItemText(61, _translate("MainWindow", "Zen Cart", None))
        self.comboBox_4.setItemText(62, _translate("MainWindow", "Yii Framework", None))
        self.comboBox_4.setItemText(63, _translate("MainWindow", "Ruby on Rails", None))
        self.comboBox_4.setItemText(64, _translate("MainWindow", "File Server", None))
        self.comboBox_4.setItemText(65, _translate("MainWindow", "WordPress", None))
        self.comboBox_4.setItemText(66, _translate("MainWindow", "Redmine", None))
        self.comboBox_4.setItemText(67, _translate("MainWindow", "OTRS", None))
        self.comboBox_4.setItemText(68, _translate("MainWindow", "MediaWiki", None))
        self.comboBox_4.setItemText(69, _translate("MainWindow", "PrestaShop", None))
        self.comboBox_4.setItemText(70, _translate("MainWindow", "LAPP", None))
        self.comboBox_4.setItemText(71, _translate("MainWindow", "Magento", None))
        self.comboBox_4.setItemText(72, _translate("MainWindow", "PostgreSQL", None))
        self.comboBox_4.setItemText(73, _translate("MainWindow", "Django", None))
        self.comboBox_4.setItemText(74, _translate("MainWindow", "LXC", None))
        self.comboBox_4.setItemText(75, _translate("MainWindow", "Observium", None))
        self.comboBox_4.setItemText(76, _translate("MainWindow", "Tendenci", None))
        self.comboBox_4.setItemText(77, _translate("MainWindow", "OpenVPN", None))
        self.comboBox_4.setItemText(78, _translate("MainWindow", "TKLDev", None))
        self.comboBox_4.setItemText(79, _translate("MainWindow", "MySQL", None))
        self.comboBox_4.setItemText(80, _translate("MainWindow", "phpBB", None))
        self.comboBox_4.setItemText(81, _translate("MainWindow", "Tomcat on Apache", None))
        self.comboBox_4.setItemText(82, _translate("MainWindow", "Standalone Tomcat", None))
        self.comboBox_4.setItemText(83, _translate("MainWindow", "MindTouch Core", None))
        self.comboBox_4.setItemText(84, _translate("MainWindow", "Tracks", None))
        self.comboBox_4.setItemText(85, _translate("MainWindow", "Symfony", None))
        self.comboBox_4.setItemText(86, _translate("MainWindow", "ProjectPier", None))
        self.comboBox_4.setItemText(87, _translate("MainWindow", "ejabberd", None))
        self.comboBox_4.setItemText(88, _translate("MainWindow", "TurnKey Core", None))
        self.comboBox_4.setItemText(89, _translate("MainWindow", "TWiki", None))
        self.comboBox_4.setItemText(90, _translate("MainWindow", "Domain Controller", None))
        self.comboBox_4.setItemText(91, _translate("MainWindow", "Revision Control", None))
        self.comboBox_4.setItemText(92, _translate("MainWindow", "Torrent Server", None))
        self.comboBox_4.setItemText(93, _translate("MainWindow", "Bugzilla", None))
        self.comboBox_4.setItemText(94, _translate("MainWindow", "Gallery", None))
        self.comboBox_4.setItemText(95, _translate("MainWindow", "Moodle", None))
        self.comboBox_4.setItemText(96, _translate("MainWindow", "Mantis", None))
        self.comboBox_4.setItemText(97, _translate("MainWindow", "Movable Type", None))
        self.comboBox_4.setItemText(98, _translate("MainWindow", "vTiger CRM", None))
        self.comboBox_4.setItemText(99, _translate("MainWindow", "StatusNet", None))
        self.comboBox_4.setItemText(100, _translate("MainWindow", "MoinMoin", None))
        self.comboBox_4.setItemText(101, _translate("MainWindow", "Roundup", None))
        self.comboBox_4.setItemText(102, _translate("MainWindow", "Trac", None))
        self.comboBox_4.setItemText(103, _translate("MainWindow", "DokuWiki", None))
        self.comboBox_4.setItemText(104, _translate("MainWindow", "Drupal 6", None))
        self.comboBox_4.setItemText(105, _translate("MainWindow", "Joomla 1.5 Appliance", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Etherpad Lite", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Joomla", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Drupal 7", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "ASP .NET on Apache with Mod Mono", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Sahana Eden", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "Ushahidi", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "GitLab", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "CouchDB", None))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "LAMP Stack", None))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "Google AppEngine on SDK", None))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "Google AppEngine Python SDK", None))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "Google AppEngine Java SDK", None))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "Elgg", None))
        self.comboBox_7.setItemText(13, _translate("MainWindow", "Concrete5", None))
        self.comboBox_7.setItemText(14, _translate("MainWindow", "eZ publish", None))
        self.comboBox_7.setItemText(15, _translate("MainWindow", "e107", None))
        self.comboBox_7.setItemText(16, _translate("MainWindow", "Collabtive", None))
        self.comboBox_7.setItemText(17, _translate("MainWindow", "CodeIgniter", None))
        self.comboBox_7.setItemText(18, _translate("MainWindow", "AppFlower", None))
        self.comboBox_7.setItemText(19, _translate("MainWindow", "b2evolution", None))
        self.comboBox_7.setItemText(20, _translate("MainWindow", "BambooInvoice", None))
        self.comboBox_7.setItemText(21, _translate("MainWindow", "MongoDB", None))
        self.comboBox_7.setItemText(22, _translate("MainWindow", "Mibew", None))
        self.comboBox_7.setItemText(23, _translate("MainWindow", "Nginx PHP FastCGI Server Configuration", None))
        self.comboBox_7.setItemText(24, _translate("MainWindow", "Clipbucket", None))
        self.comboBox_7.setItemText(25, _translate("MainWindow", "Canvas", None))
        self.comboBox_7.setItemText(26, _translate("MainWindow", "CakePHP", None))
        self.comboBox_7.setItemText(27, _translate("MainWindow", "node.js", None))
        self.comboBox_7.setItemText(28, _translate("MainWindow", "iceScrum", None))
        self.comboBox_7.setItemText(29, _translate("MainWindow", "Jenkins", None))
        self.comboBox_7.setItemText(30, _translate("MainWindow", "Mambo", None))
        self.comboBox_7.setItemText(31, _translate("MainWindow", "Mahara", None))
        self.comboBox_7.setItemText(32, _translate("MainWindow", "Lighttpd PHP FastCGI Configuration", None))
        self.comboBox_7.setItemText(33, _translate("MainWindow", "OpenLDAP", None))
        self.comboBox_7.setItemText(34, _translate("MainWindow", "osCommerce", None))
        self.comboBox_7.setItemText(35, _translate("MainWindow", "Omeka", None))
        self.comboBox_7.setItemText(36, _translate("MainWindow", "Plone", None))
        self.comboBox_7.setItemText(37, _translate("MainWindow", "LimeSurvey", None))
        self.comboBox_7.setItemText(38, _translate("MainWindow", "OrangeHRM", None))
        self.comboBox_7.setItemText(39, _translate("MainWindow", "OpenPhoto", None))
        self.comboBox_7.setItemText(40, _translate("MainWindow", "Piwik", None))
        self.comboBox_7.setItemText(41, _translate("MainWindow", "Pligg", None))
        self.comboBox_7.setItemText(42, _translate("MainWindow", "SilverStripe", None))
        self.comboBox_7.setItemText(43, _translate("MainWindow", "PunBB", None))
        self.comboBox_7.setItemText(44, _translate("MainWindow", "ProcessMaker", None))
        self.comboBox_7.setItemText(45, _translate("MainWindow", "Sencha", None))
        self.comboBox_7.setItemText(46, _translate("MainWindow", "OSQA", None))
        self.comboBox_7.setItemText(47, _translate("MainWindow", "ownCloud", None))
        self.comboBox_7.setItemText(48, _translate("MainWindow", "phpList", None))
        self.comboBox_7.setItemText(49, _translate("MainWindow", "PHP-Nuke", None))
        self.comboBox_7.setItemText(50, _translate("MainWindow", "Vanilla Forum", None))
        self.comboBox_7.setItemText(51, _translate("MainWindow", "web2py", None))
        self.comboBox_7.setItemText(52, _translate("MainWindow", "Phreedom", None))
        self.comboBox_7.setItemText(53, _translate("MainWindow", "Typo3", None))
        self.comboBox_7.setItemText(54, _translate("MainWindow", "TomatoCart", None))
        self.comboBox_7.setItemText(55, _translate("MainWindow", "XOOPS", None))
        self.comboBox_7.setItemText(56, _translate("MainWindow", "Zurmo", None))
        self.comboBox_7.setItemText(57, _translate("MainWindow", "SiT! Support Incident Tracker", None))
        self.comboBox_7.setItemText(58, _translate("MainWindow", "SimpleInvoices", None))
        self.comboBox_7.setItemText(59, _translate("MainWindow", "SimpleMachines", None))
        self.comboBox_7.setItemText(60, _translate("MainWindow", "SugarCRM", None))
        self.comboBox_7.setItemText(61, _translate("MainWindow", "Zen Cart", None))
        self.comboBox_7.setItemText(62, _translate("MainWindow", "Yii Framework", None))
        self.comboBox_7.setItemText(63, _translate("MainWindow", "Ruby on Rails", None))
        self.comboBox_7.setItemText(64, _translate("MainWindow", "File Server", None))
        self.comboBox_7.setItemText(65, _translate("MainWindow", "WordPress", None))
        self.comboBox_7.setItemText(66, _translate("MainWindow", "Redmine", None))
        self.comboBox_7.setItemText(67, _translate("MainWindow", "OTRS", None))
        self.comboBox_7.setItemText(68, _translate("MainWindow", "MediaWiki", None))
        self.comboBox_7.setItemText(69, _translate("MainWindow", "PrestaShop", None))
        self.comboBox_7.setItemText(70, _translate("MainWindow", "LAPP", None))
        self.comboBox_7.setItemText(71, _translate("MainWindow", "Magento", None))
        self.comboBox_7.setItemText(72, _translate("MainWindow", "PostgreSQL", None))
        self.comboBox_7.setItemText(73, _translate("MainWindow", "Django", None))
        self.comboBox_7.setItemText(74, _translate("MainWindow", "LXC", None))
        self.comboBox_7.setItemText(75, _translate("MainWindow", "Observium", None))
        self.comboBox_7.setItemText(76, _translate("MainWindow", "Tendenci", None))
        self.comboBox_7.setItemText(77, _translate("MainWindow", "OpenVPN", None))
        self.comboBox_7.setItemText(78, _translate("MainWindow", "TKLDev", None))
        self.comboBox_7.setItemText(79, _translate("MainWindow", "MySQL", None))
        self.comboBox_7.setItemText(80, _translate("MainWindow", "phpBB", None))
        self.comboBox_7.setItemText(81, _translate("MainWindow", "Tomcat on Apache", None))
        self.comboBox_7.setItemText(82, _translate("MainWindow", "Standalone Tomcat", None))
        self.comboBox_7.setItemText(83, _translate("MainWindow", "MindTouch Core", None))
        self.comboBox_7.setItemText(84, _translate("MainWindow", "Tracks", None))
        self.comboBox_7.setItemText(85, _translate("MainWindow", "Symfony", None))
        self.comboBox_7.setItemText(86, _translate("MainWindow", "ProjectPier", None))
        self.comboBox_7.setItemText(87, _translate("MainWindow", "ejabberd", None))
        self.comboBox_7.setItemText(88, _translate("MainWindow", "TurnKey Core", None))
        self.comboBox_7.setItemText(89, _translate("MainWindow", "TWiki", None))
        self.comboBox_7.setItemText(90, _translate("MainWindow", "Domain Controller", None))
        self.comboBox_7.setItemText(91, _translate("MainWindow", "Revision Control", None))
        self.comboBox_7.setItemText(92, _translate("MainWindow", "Torrent Server", None))
        self.comboBox_7.setItemText(93, _translate("MainWindow", "Bugzilla", None))
        self.comboBox_7.setItemText(94, _translate("MainWindow", "Gallery", None))
        self.comboBox_7.setItemText(95, _translate("MainWindow", "Moodle", None))
        self.comboBox_7.setItemText(96, _translate("MainWindow", "Mantis", None))
        self.comboBox_7.setItemText(97, _translate("MainWindow", "Movable Type", None))
        self.comboBox_7.setItemText(98, _translate("MainWindow", "vTiger CRM", None))
        self.comboBox_7.setItemText(99, _translate("MainWindow", "StatusNet", None))
        self.comboBox_7.setItemText(100, _translate("MainWindow", "MoinMoin", None))
        self.comboBox_7.setItemText(101, _translate("MainWindow", "Roundup", None))
        self.comboBox_7.setItemText(102, _translate("MainWindow", "Trac", None))
        self.comboBox_7.setItemText(103, _translate("MainWindow", "DokuWiki", None))
        self.comboBox_7.setItemText(104, _translate("MainWindow", "Drupal 6", None))
        self.comboBox_7.setItemText(105, _translate("MainWindow", "Joomla 1.5 Appliance", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Etherpad Lite", None))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Joomla", None))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "Drupal 7", None))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "ASP .NET on Apache with Mod Mono", None))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "Sahana Eden", None))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "Ushahidi", None))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "GitLab", None))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "CouchDB", None))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "LAMP Stack", None))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "Google AppEngine on SDK", None))
        self.comboBox_10.setItemText(10, _translate("MainWindow", "Google AppEngine Python SDK", None))
        self.comboBox_10.setItemText(11, _translate("MainWindow", "Google AppEngine Java SDK", None))
        self.comboBox_10.setItemText(12, _translate("MainWindow", "Elgg", None))
        self.comboBox_10.setItemText(13, _translate("MainWindow", "Concrete5", None))
        self.comboBox_10.setItemText(14, _translate("MainWindow", "eZ publish", None))
        self.comboBox_10.setItemText(15, _translate("MainWindow", "e107", None))
        self.comboBox_10.setItemText(16, _translate("MainWindow", "Collabtive", None))
        self.comboBox_10.setItemText(17, _translate("MainWindow", "CodeIgniter", None))
        self.comboBox_10.setItemText(18, _translate("MainWindow", "AppFlower", None))
        self.comboBox_10.setItemText(19, _translate("MainWindow", "b2evolution", None))
        self.comboBox_10.setItemText(20, _translate("MainWindow", "BambooInvoice", None))
        self.comboBox_10.setItemText(21, _translate("MainWindow", "MongoDB", None))
        self.comboBox_10.setItemText(22, _translate("MainWindow", "Mibew", None))
        self.comboBox_10.setItemText(23, _translate("MainWindow", "Nginx PHP FastCGI Server Configuration", None))
        self.comboBox_10.setItemText(24, _translate("MainWindow", "Clipbucket", None))
        self.comboBox_10.setItemText(25, _translate("MainWindow", "Canvas", None))
        self.comboBox_10.setItemText(26, _translate("MainWindow", "CakePHP", None))
        self.comboBox_10.setItemText(27, _translate("MainWindow", "node.js", None))
        self.comboBox_10.setItemText(28, _translate("MainWindow", "iceScrum", None))
        self.comboBox_10.setItemText(29, _translate("MainWindow", "Jenkins", None))
        self.comboBox_10.setItemText(30, _translate("MainWindow", "Mambo", None))
        self.comboBox_10.setItemText(31, _translate("MainWindow", "Mahara", None))
        self.comboBox_10.setItemText(32, _translate("MainWindow", "Lighttpd PHP FastCGI Configuration", None))
        self.comboBox_10.setItemText(33, _translate("MainWindow", "OpenLDAP", None))
        self.comboBox_10.setItemText(34, _translate("MainWindow", "osCommerce", None))
        self.comboBox_10.setItemText(35, _translate("MainWindow", "Omeka", None))
        self.comboBox_10.setItemText(36, _translate("MainWindow", "Plone", None))
        self.comboBox_10.setItemText(37, _translate("MainWindow", "LimeSurvey", None))
        self.comboBox_10.setItemText(38, _translate("MainWindow", "OrangeHRM", None))
        self.comboBox_10.setItemText(39, _translate("MainWindow", "OpenPhoto", None))
        self.comboBox_10.setItemText(40, _translate("MainWindow", "Piwik", None))
        self.comboBox_10.setItemText(41, _translate("MainWindow", "Pligg", None))
        self.comboBox_10.setItemText(42, _translate("MainWindow", "SilverStripe", None))
        self.comboBox_10.setItemText(43, _translate("MainWindow", "PunBB", None))
        self.comboBox_10.setItemText(44, _translate("MainWindow", "ProcessMaker", None))
        self.comboBox_10.setItemText(45, _translate("MainWindow", "Sencha", None))
        self.comboBox_10.setItemText(46, _translate("MainWindow", "OSQA", None))
        self.comboBox_10.setItemText(47, _translate("MainWindow", "ownCloud", None))
        self.comboBox_10.setItemText(48, _translate("MainWindow", "phpList", None))
        self.comboBox_10.setItemText(49, _translate("MainWindow", "PHP-Nuke", None))
        self.comboBox_10.setItemText(50, _translate("MainWindow", "Vanilla Forum", None))
        self.comboBox_10.setItemText(51, _translate("MainWindow", "web2py", None))
        self.comboBox_10.setItemText(52, _translate("MainWindow", "Phreedom", None))
        self.comboBox_10.setItemText(53, _translate("MainWindow", "Typo3", None))
        self.comboBox_10.setItemText(54, _translate("MainWindow", "TomatoCart", None))
        self.comboBox_10.setItemText(55, _translate("MainWindow", "XOOPS", None))
        self.comboBox_10.setItemText(56, _translate("MainWindow", "Zurmo", None))
        self.comboBox_10.setItemText(57, _translate("MainWindow", "SiT! Support Incident Tracker", None))
        self.comboBox_10.setItemText(58, _translate("MainWindow", "SimpleInvoices", None))
        self.comboBox_10.setItemText(59, _translate("MainWindow", "SimpleMachines", None))
        self.comboBox_10.setItemText(60, _translate("MainWindow", "SugarCRM", None))
        self.comboBox_10.setItemText(61, _translate("MainWindow", "Zen Cart", None))
        self.comboBox_10.setItemText(62, _translate("MainWindow", "Yii Framework", None))
        self.comboBox_10.setItemText(63, _translate("MainWindow", "Ruby on Rails", None))
        self.comboBox_10.setItemText(64, _translate("MainWindow", "File Server", None))
        self.comboBox_10.setItemText(65, _translate("MainWindow", "WordPress", None))
        self.comboBox_10.setItemText(66, _translate("MainWindow", "Redmine", None))
        self.comboBox_10.setItemText(67, _translate("MainWindow", "OTRS", None))
        self.comboBox_10.setItemText(68, _translate("MainWindow", "MediaWiki", None))
        self.comboBox_10.setItemText(69, _translate("MainWindow", "PrestaShop", None))
        self.comboBox_10.setItemText(70, _translate("MainWindow", "LAPP", None))
        self.comboBox_10.setItemText(71, _translate("MainWindow", "Magento", None))
        self.comboBox_10.setItemText(72, _translate("MainWindow", "PostgreSQL", None))
        self.comboBox_10.setItemText(73, _translate("MainWindow", "Django", None))
        self.comboBox_10.setItemText(74, _translate("MainWindow", "LXC", None))
        self.comboBox_10.setItemText(75, _translate("MainWindow", "Observium", None))
        self.comboBox_10.setItemText(76, _translate("MainWindow", "Tendenci", None))
        self.comboBox_10.setItemText(77, _translate("MainWindow", "OpenVPN", None))
        self.comboBox_10.setItemText(78, _translate("MainWindow", "TKLDev", None))
        self.comboBox_10.setItemText(79, _translate("MainWindow", "MySQL", None))
        self.comboBox_10.setItemText(80, _translate("MainWindow", "phpBB", None))
        self.comboBox_10.setItemText(81, _translate("MainWindow", "Tomcat on Apache", None))
        self.comboBox_10.setItemText(82, _translate("MainWindow", "Standalone Tomcat", None))
        self.comboBox_10.setItemText(83, _translate("MainWindow", "MindTouch Core", None))
        self.comboBox_10.setItemText(84, _translate("MainWindow", "Tracks", None))
        self.comboBox_10.setItemText(85, _translate("MainWindow", "Symfony", None))
        self.comboBox_10.setItemText(86, _translate("MainWindow", "ProjectPier", None))
        self.comboBox_10.setItemText(87, _translate("MainWindow", "ejabberd", None))
        self.comboBox_10.setItemText(88, _translate("MainWindow", "TurnKey Core", None))
        self.comboBox_10.setItemText(89, _translate("MainWindow", "TWiki", None))
        self.comboBox_10.setItemText(90, _translate("MainWindow", "Domain Controller", None))
        self.comboBox_10.setItemText(91, _translate("MainWindow", "Revision Control", None))
        self.comboBox_10.setItemText(92, _translate("MainWindow", "Torrent Server", None))
        self.comboBox_10.setItemText(93, _translate("MainWindow", "Bugzilla", None))
        self.comboBox_10.setItemText(94, _translate("MainWindow", "Gallery", None))
        self.comboBox_10.setItemText(95, _translate("MainWindow", "Moodle", None))
        self.comboBox_10.setItemText(96, _translate("MainWindow", "Mantis", None))
        self.comboBox_10.setItemText(97, _translate("MainWindow", "Movable Type", None))
        self.comboBox_10.setItemText(98, _translate("MainWindow", "vTiger CRM", None))
        self.comboBox_10.setItemText(99, _translate("MainWindow", "StatusNet", None))
        self.comboBox_10.setItemText(100, _translate("MainWindow", "MoinMoin", None))
        self.comboBox_10.setItemText(101, _translate("MainWindow", "Roundup", None))
        self.comboBox_10.setItemText(102, _translate("MainWindow", "Trac", None))
        self.comboBox_10.setItemText(103, _translate("MainWindow", "DokuWiki", None))
        self.comboBox_10.setItemText(104, _translate("MainWindow", "Drupal 6", None))
        self.comboBox_10.setItemText(105, _translate("MainWindow", "Joomla 1.5 Appliance", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "VirtualBox", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "VMWare", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Xen", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "VirtualBox", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "VMWare", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Xen", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "VirtualBox", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "VMWare", None))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "Xen", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "VirtualBox", None))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "VMWare", None))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "Xen", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "SSH", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "SSH", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "SSH", None))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "SSH", None))
        self.lineEdit_9.setText(_translate("MainWindow", "Password", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))
        self.actionUpdate_Apps.setText(_translate("MainWindow", "Update Apps", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

